### ISSUE TITLE
Prep work for cryptoswap sims

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#123]
Let's wrap up all the loose threads and blockers needed to proceed smoothly with the cryptoswap sim work:

`SimPool` interface
--------------------
- [x] #121 
- [x] #122 
- [x] #127

`Trader`
---------------
- [x] make the trade types explicit (there are two: one as trades to be executed, and one that is the result or "receipt")
- [x] #129

`SimCurveCryptoPool`
-----------------------
- [ ] `price`
- [ ] `get_input_amount`
- [ ] misc methods: `prepare_for_trades`, `number_of_coins`, `assets`

**Comment by chanhosuh** [comment]
0.4.5 has been released!  `SimCurveCryptoPool` will be part of the cryptosim milestone.
